name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # Roda o deploy toda vez que um commit é feito na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar autenticação no Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Instalar gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "api-bling-450013"  # Substitua pelo ID do seu projeto no Google Cloud

      - name: Fazer deploy no App Engine
        run: gcloud app deploy --quiet
